export { default as Currencies } from './currencies.component'
export { default as MoneyControl } from './moneycontrol.component'
export { default as News } from './news.component'
export { default as SideBar } from './sidebar.component'
export { default as DashBoard } from './dashboard.component'
export { default as CurrencyCard } from './currency.card.component'